---

include:
  - component: $CI_SERVER_FQDN/components/code-quality-oss/codequality-os-scanners-integration/golangci@1.0.7
    inputs:
      convert_to_sast: true
stages:
  - test
  - build
  - release

variables:
  GOPATH: $CI_PROJECT_DIR/.go

.go_cache: &go_cache
  key:
    files:
      - go.sum
  paths:
    - .go/

.parallel: &parallel
  matrix:
    - GOOS: linux
      GOARCH:
        - amd64
        - arm64
    - GOOS: darwin
      GOARCH:
        - amd64
        - arm64
    - GOOS: windows
      GOARCH:
        - amd64

build:
  stage: build
  image: golang:1.24.2
  needs: []
  cache: *go_cache
  before_script:
    - make prepare
  script:
    - make build
  artifacts:
    name: "artifacts-$GOOS-$GOARCH"
    paths:
      - bin/$GOOS/$GOARCH/
  parallel: *parallel

release:upload:
  stage: release
  image: curlimages/curl:latest
  rules:
    - if: $CI_COMMIT_TAG
  dependencies:
    - build
  script:
    - build/ci-upload.sh

release:release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli
  rules:
    - if: $CI_COMMIT_TAG
  dependencies:
    - build
  script:
    - build/ci-release.sh
